# Generated by Django 5.1 on 2024-08-26 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goals',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goals',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
