# Generated by Django 5.1 on 2024-08-27 11:31

from django.db import migrations, models

def forward_func(apps, schema):
    model = apps.get_model("notes", "Goals")
    for obj in model.objects.all():
        obj.miniGoalsNum = len(obj.miniGoals.split("###"))
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_goals_date_alter_goals_done_alter_goals_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='miniGoalsNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(forward_func),
        migrations.AddField(
            model_name='goals',
            name='miniGoalsState',
            field=models.IntegerField(default=0),
        ),
    ]
