# Generated by Django 5.1 on 2024-08-27 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_goals_minigoalsnum_goals_minigoalsstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminders',
            name='done',
        ),
        migrations.AddField(
            model_name='reminders',
            name='dead_line',
            field=models.TimeField(default="4:4"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminders',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
