# Generated by Django 5.1 on 2024-08-27 21:31

import django.db.models.deletion
from django.db import migrations, models





class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_reminders_done_reminders_dead_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('num_notes', models.IntegerField()),
                ('num_notes_completed', models.IntegerField()),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('days_progress', models.TextField()),
                ('state', models.BooleanField()),
            ],
        ),
    ]
