# Generated by Django 5.1 on 2024-08-27 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20240828_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='Month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.month'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.day'),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.day'),
        ),
    ]
