# Generated by Django 5.1 on 2024-08-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_goals_month_alter_notes_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='Month',
            new_name='month',
        ),
    ]
