# Generated by Django 5.1 on 2024-08-31 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_func(apps, schema):
    month = apps.get_model("notes", "Month")
    day = apps.get_model("notes", "Day")

    for month in month.objects.all():
        month.user = month.day_set.all()[0].notes_set.all()[0].user
        month.save()

    for day in day.objects.all():
        day.user = day.notes_set.all()[0].user
        day.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_rename_month_goals_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(forward_func)
    ]
