# Generated by Django 5.1 on 2024-08-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_day_user_month_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
