# Generated by Django 5.1 on 2024-08-31 12:05

from django.db import migrations

def forward_func(apps, schema):
    Goals = apps.get_model("notes", "Goals")

    for goal in Goals.objects.all():
        goal.date_planned = goal.date_planned.replace(day=1)
        goal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_alter_day_num_notes_alter_day_num_notes_completed'),
    ]

    operations = [
        migrations.RunPython(forward_func),
    ]
