# Generated by Django 5.1 on 2024-09-04 21:45

from django.db import migrations, models
import random
def func(apps, shema):
    Goals = apps.get_model("notes", "Goals")
    for goal in Goals.objects.all():
        goal.theme = random.randint(1,4)
        goal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_notes_category_notes_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='theme',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(func),
    ]
