# Generated by Django 5.1 on 2024-09-06 12:39

from django.db import migrations
import calendar, math
def set_initial_progress(self):
        progress = ""
        for day in range(1, calendar.monthrange(year=self.month.year, month=self.month.month)[1]):
            progress += "0#"
        progress += "0"
        self.days_progress=progress
        self.save()

def func(apps, schema):
    Month = apps.get_model("notes", "Month")
    for month in Month.objects.all():
        set_initial_progress(month)
        days = month.day_set.all()
        for day in days:
            days_progress = month.days_progress.split("#")
            if day.num_notes:
                days_progress[day.day-1] = str(math.floor(day.num_notes_completed/day.num_notes * 100))
            month.days_progress = "#".join(days_progress)
            month.save()

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_goals_theme_notes_edited'),
    ]

    operations = [
         migrations.RunPython(func)
    ]
