# Generated by Django 5.1 on 2024-09-07 10:19

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_month_num_notes_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='month_photo',
            field=models.ImageField(default='default/month-image.png', upload_to=notes.models.month_image_storage),
        ),
    ]
