# Generated by Django 5.1 on 2024-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_month_month_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
