# Generated by Django 4.2.16 on 2024-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_remove_goals_theme_remove_notes_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='theme',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.CharField(choices=[('SD', 'self_development'), ('SL', 'social_life'), ('LS', 'life_style')], default='SD', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='theme',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
            preserve_default=False,
        ),
    ]
