# Generated by Django 5.1 on 2024-09-09 11:46

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default/month-image.png', upload_to=authentication.models.profile_image_storage),
        ),
    ]
