# Generated by Django 5.1 on 2024-09-09 15:07

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default/profile-image.jpg', upload_to=authentication.models.profile_image_storage),
        ),
    ]
